open_orchestra_base_node_preview:
    path: %open_orchestra_base.preview_route_pattern%

open_orchestra_base_node_preview_with_prefix:
    path: %open_orchestra_base.preview_with_prefix_route_pattern%
