parameters:
    php_orchestra_base.listener.locale.class : 'PHPOrchestra\BaseBundle\EventListener\LocaleListener'

services:
    # Locale listener
    php_orchestra_base.locale_listener:
        class: %php_orchestra_base.listener.locale.class%
        arguments: [%kernel.default_locale%]
        tags: [{name: kernel.event_subscriber}]
