parameters:
#    php_orchestra_base.example.class: PHPOrchestra\BaseBundle\Example

services:
#    php_orchestra_base.example:
#        class: %php_orchestra_base.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
